// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEwMojvM73UFbJn0fGpx9eYvSDASnHLA',
    appId: '1:356715585015:web:3729c9dddd3396d427e2f2',
    messagingSenderId: '356715585015',
    projectId: 'ngu-room-reservation',
    authDomain: 'ngu-room-reservation.firebaseapp.com',
    storageBucket: 'ngu-room-reservation.firebasestorage.app',
    measurementId: 'G-5M1J3HM5C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2kRiv5HHobdB1DrhOmgWy0rF_T3zax0',
    appId: '1:356715585015:android:11f08d703c300e2527e2f2',
    messagingSenderId: '356715585015',
    projectId: 'ngu-room-reservation',
    storageBucket: 'ngu-room-reservation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8o5yDVPHnECFbW1UHou45NMEx2xzdxjw',
    appId: '1:356715585015:ios:144043ecb1785eb727e2f2',
    messagingSenderId: '356715585015',
    projectId: 'ngu-room-reservation',
    storageBucket: 'ngu-room-reservation.firebasestorage.app',
    iosBundleId: 'com.example.nguProject',
  );
}
